# Generated by Django 5.0.1 on 2024-01-28 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_recipt',
            field=models.FileField(null=True, upload_to='payment_recipts/'),
        ),
        migrations.AddField(
            model_name='payment',
            name='remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='apartment_type',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='area',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='balcony_area',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='bedroom_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='block',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='common_area',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='extra_balconies',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='floor',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='gross_area',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='has_generator',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='has_lift',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='has_parking',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='has_water_pump',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='house_no',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='property',
            name='kitchen',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='living_room',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='marketing_director',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='net_area',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='plan_pdf',
            field=models.FileField(null=True, upload_to='property_plans/'),
        ),
        migrations.AddField(
            model_name='property',
            name='position_floor',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='project_type',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='receiver_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='status',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='subcity',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='supervisor_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='toilet',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='total_area',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='total_units_area',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='view',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='woreda',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sales',
            name='agreement_number',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sales',
            name='branch',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sales',
            name='contract_amount_birr',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='sales',
            name='contract_document',
            field=models.FileField(null=True, upload_to='contract_documents/'),
        ),
        migrations.AddField(
            model_name='sales',
            name='delivery_date_in_months',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='sales',
            name='discount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='sales',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='sales',
            name='finish_type',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sales',
            name='payment_plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sales.paymentplan'),
        ),
        migrations.AddField(
            model_name='sales',
            name='property_type',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sales',
            name='remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sales',
            name='sales_consultant',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sales',
            name='sales_supervisor',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sales',
            name='sold_via',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sales',
            name='total_paid_percent',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='sales',
            name='unit_price_usd',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
