# Generated by Django 5.0.1 on 2024-01-28 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_payment_payment_recipt_payment_remark_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='kitchen',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='living_room',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='toilet',
            field=models.IntegerField(null=True),
        ),
    ]
