# Generated by Django 5.0.1 on 2024-01-28 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_alter_property_kitchen_alter_property_living_room_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='due_date',
            field=models.DateField(),
        ),
    ]
