# Generated by Django 4.2.9 on 2024-01-29 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_alter_payment_due_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='plan_pdf',
        ),
    ]
