# Generated by Django 4.2.9 on 2024-02-09 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_payment_installment_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BalconyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyLootNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loot_number', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UnitType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='property',
            name='receiver_name',
        ),
        migrations.RemoveField(
            model_name='property',
            name='size',
        ),
        migrations.AddField(
            model_name='property',
            name='site',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='balcony_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sales.balconytype'),
        ),
        migrations.AddField(
            model_name='property',
            name='loot_number',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sales.propertylootnumber'),
        ),
        migrations.AddField(
            model_name='property',
            name='unit_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sales.unittype'),
        ),
        migrations.AlterField(
            model_name='property',
            name='block',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sales.propertyblock'),
        ),
    ]
