# Generated by Django 4.2.9 on 2024-03-15 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0011_payment_agreement_number_payment_percentage_paid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='prepared_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
