# Generated by Django 4.2.9 on 2024-03-19 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0013_alter_payment_prepared_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='agreement_number',
            field=models.CharField(blank=True, help_text='* The agreement number for this payment', max_length=100, null=True),
        ),
    ]
