# Generated by Django 5.0.1 on 2024-01-17 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_employee_last_id_no_employee_photo_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='id_no',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
